<?php

namespace Database\Seeders;

use App\Models\Admin\GameList;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PGSoftGameListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'code' => '1',
                'name' => 'Honey Trap of Diao Chan',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Honey_Trap_of_Diao_Chan.png',
            ],
            [
                'code' => '2',
                'name' => 'Gem Saviour',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Gem_Saviour.png',
            ],
            [
                'code' => '31',
                'name' => 'Fortune Gods',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Fortune_Gods.png',
            ],
            [
                'code' => '6',
                'name' => 'Medusa 2: The Quest of Perseus',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Medusa_2.png',
            ],
            [
                'code' => '7',
                'name' => 'Medusa 1: The Curse of Athena',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Medusa_1.png',
            ],
            [
                'code' => '18',
                'name' => 'Hood vs Wolf',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Hood_vs_Wolf.png',
            ],
            [
                'code' => '20',
                'name' => 'Reel Love',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Reel_Love.png',
            ],
            [
                'code' => '24',
                'name' => 'Win Win Won',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Win_Win_Won.png',
            ],
            [
                'code' => '25',
                'name' => 'Plushie Frenzy',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Plushie_Frenzy.png',
            ],
            [
                'code' => '26',
                'name' => 'Tree of Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Tree_of_Fortune.png',
            ],
            [
                'code' => '28',
                'name' => 'Hotpot',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Hotpot.png',
            ],
            [
                'code' => '29',
                'name' => 'Dragon Legend',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Dragon_Legend.png',
            ],
            [
                'code' => '33',
                'name' => 'Hip Hop Panda',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Hip_Hop_Panda.png',
            ],
            [
                'code' => '34',
                'name' => 'Legend of Hou Yi',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Legend_of_Hou_Yi.png',
            ],
            [
                'code' => '35',
                'name' => 'Mr. Hallow-Win',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mr._Hallow-Win.png',
            ],
            [
                'code' => '36',
                'name' => 'Prosperity Lion',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Prosperity_Lion.png',
            ],
            [
                'code' => '37',
                'name' => 'Santa\'s Gift Rush',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Santa\'s_Gift_Rush.png',
            ],
            [
                'code' => '1',
                'name' => 'Honey Trap of Diao Chan',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Honey_Trap_of_Diao_Chan.png',
            ],
            [
                'code' => '2',
                'name' => 'Gem Saviour',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Gem_Saviour.png',
            ],
            [
                'code' => '31',
                'name' => 'Fortune Gods',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Fortune_Gods.png',
            ],
            [
                'code' => '6',
                'name' => 'Medusa 2: The Quest of Perseus',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Medusa_2.png',
            ],
            [
                'code' => '7',
                'name' => 'Medusa 1: The Curse of Athena',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Medusa_1.png',
            ],
            [
                'code' => '18',
                'name' => 'Hood vs Wolf',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Hood_vs_Wolf.png',
            ],
            [
                'code' => '20',
                'name' => 'Reel Love',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Reel_Love.png',
            ],
            [
                'code' => '24',
                'name' => 'Win Win Won',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Win_Win_Won.png',
            ],
            [
                'code' => '25',
                'name' => 'Plushie Frenzy',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Plushie_Frenzy.png',
            ],
            [
                'code' => '26',
                'name' => 'Tree of Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Tree_of_Fortune.png',
            ],
            [
                'code' => '28',
                'name' => 'Hotpot',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Hotpot.png',
            ],
            [
                'code' => '29',
                'name' => 'Dragon Legend',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Dragon_Legend.png',
            ],
            [
                'code' => '33',
                'name' => 'Hip Hop Panda',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Hip_Hop_Panda.png',
            ],
            [
                'code' => '34',
                'name' => 'Legend of Hou Yi',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Legend_of_Hou_Yi.png',
            ],
            [
                'code' => '35',
                'name' => 'Mr. Hallow-Win',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mr._Hallow-Win.png',
            ],
            [
                'code' => '36',
                'name' => 'Prosperity Lion',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Prosperity_Lion.png',
            ],
            [
                'code' => '37',
                'name' => 'Santa\'s Gift Rush',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Santa\'s_Gift_Rush.png',
            ],
            [
                'code' => '38',
                'name' => 'Gem Saviour Sword',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Gem_Saviour_Sword.png',
            ],
            [
                'code' => '39',
                'name' => 'Piggy Gold',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Piggy_Gold.png',
            ],
            [
                'code' => '40',
                'name' => 'Jungle Delight',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Jungle_Delight.png',
            ],
            [
                'code' => '41',
                'name' => 'Symbols Of Egypt',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Symbols_Of_Egypt.png',
            ],
            [
                'code' => '42',
                'name' => 'Ganesha Gold',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Ganesha_Gold.png',
            ],
            [
                'code' => '44',
                'name' => 'Emperor\'s Favour',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Emperor\'s_Favour.png',
            ],
            [
                'code' => '48',
                'name' => 'Double Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Double_Fortune.png',
            ],
            [
                'code' => '50',
                'name' => 'Journey to the Wealth',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Journey_to_the_Wealth.png',
            ],
            [
                'code' => '53',
                'name' => 'The Great Icescape',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/The_Great_Icescape.png',
            ],
            [
                'code' => '54',
                'name' => 'Captain\'s Bounty',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Captain\'s_Bounty.png',
            ],
            [
                'code' => '57',
                'name' => 'Dragon Hatch',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Dragon_Hatch.png',
            ],
            [
                'code' => '58',
                'name' => 'Vampire\'s Charm',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Vampire\'s_Charm.png',
            ],
            [
                'code' => '59',
                'name' => 'Ninja vs Samurai',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Ninja_vs_Samurai.png',
            ],
            [
                'code' => '60',
                'name' => 'Leprechaun Riches',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Leprechaun_Riches.png',
            ],
            [
                'code' => '61',
                'name' => 'Flirting Scholar',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Flirting_Scholar.png',
            ],
            [
                'code' => '62',
                'name' => 'Gem Saviour Conquest',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Gem_Saviour_Conquest.png',
            ],
            [
                'code' => '63',
                'name' => 'Dragon Tiger Luck',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Dragon_Tiger_Luck.png',
            ],
            [
                'code' => '64',
                'name' => 'Muay Thai Champion',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Muay_Thai_Champion.png',
            ],
            [
                'code' => '65',
                'name' => 'Mahjong Ways',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mahjong_Ways.png',
            ],
            [
                'code' => '67',
                'name' => 'Shaolin Soccer',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Shaolin_Soccer.png',
            ],
            [
                'code' => '68',
                'name' => 'Fortune Mouse',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Fortune_Mouse.png',
            ],
            [
                'code' => '69',
                'name' => 'Bikini Paradise',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Bikini_Paradise.png',
            ],
            [
                'code' => '70',
                'name' => 'Candy Burst',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Candy_Burst.png',
            ],
            [
                'code' => '71',
                'name' => 'CaiShen Wins',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/CaiShen_Wins.png',
            ],
            [
                'code' => '73',
                'name' => 'Egypt\'s Book of Mystery',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Egypt\'s_Book_of_Mystery.png',
            ],
            [
                'code' => '74',
                'name' => 'Mahjong Ways 2',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mahjong_Ways_2.png',
            ],
            [
                'code' => '75',
                'name' => 'Ganesha Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Ganesha_Fortune.png',
            ],
            [
                'code' => '79',
                'name' => 'Dreams of Macau',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Dreams_of_Macau.png',
            ],
            [
                'code' => '80',
                'name' => 'Circus Delight',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Circus_Delight.png',
            ],
            [
                'code' => '82',
                'name' => 'Phoenix Rises',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Phoenix_Rises.png',
            ],
            [
                'code' => '83',
                'name' => 'Wild Fireworks',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Wild_Fireworks.png',
            ],
            [
                'code' => '84',
                'name' => 'Queen of Bounty',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Queen_of_Bounty.png',
            ],
            [
                'code' => '85',
                'name' => 'Genie\'s 31 Wishes',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Genie\'s_3_Wishes.png',
            ],
            [
                'code' => '86',
                'name' => 'Galactic Gems',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Galactic_Gems.png',
            ],
            [
                'code' => '87',
                'name' => 'Treasures of Aztec',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Treasures_of_Aztec.png',
            ],
            [
                'code' => '88',
                'name' => 'Jewels of Prosperity',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Jewels_of_Prosperity.png',
            ],
            [
                'code' => '89',
                'name' => 'Lucky Neko',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Lucky_Neko.png',
            ],
            [
                'code' => '90',
                'name' => 'Secrets of Cleopatra',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Secrets_of_Cleopatra.png',
            ],
            [
                'code' => '91',
                'name' => 'Guardians of Ice & Fire',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Guardians_of_Ice_&_Fire.png',
            ],
            [
                'code' => '92',
                'name' => 'Thai River Wonders',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Thai_River_Wonders.png',
            ],
            [
                'code' => '93',
                'name' => 'Opera Dynasty',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Opera_Dynasty.png',
            ],
            [
                'code' => '94',
                'name' => 'Bali Vacation',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Bali_Vacation.png',
            ],
            [
                'code' => '95',
                'name' => 'Majestic Treasures',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Majestic_Treasures.png',
            ],
            [
                'code' => '97',
                'name' => 'Jack Frost\'s Winter',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Jack_Frost\'s_Winter.png',
            ],
            [
                'code' => '98',
                'name' => 'Fortune Ox',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Fortune_Ox.png',
            ],
            [
                'code' => '100',
                'name' => 'Candy Bonanza',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Candy_Bonanza.png',
            ],
            [
                'code' => '101',
                'name' => 'Rise of Apollo',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Rise_of_Apollo.png',
            ],
            [
                'code' => '102',
                'name' => 'Mermaid Riches',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mermaid_Riches.png',
            ],
            [
                'code' => '103',
                'name' => 'Crypto Gold',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Crypto_Gold.png',
            ],
            [
                'code' => '104',
                'name' => 'Wild Bandito',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Wild_Bandito.png',
            ],
            [
                'code' => '105',
                'name' => 'Heist Stakes',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Heist_Stakes.png',
            ],
            [
                'code' => '106',
                'name' => 'Ways of the Qilin',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Ways_of_the_Qilin.png',
            ],
            [
                'code' => '107',
                'name' => 'Legendary Monkey King',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Legendary_Monkey_King.png',
            ],
            [
                'code' => '108',
                'name' => 'Buffalo Win',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Buffalo_Win.png',
            ],
            [
                'code' => '110',
                'name' => 'Jurassic Kingdom',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Jurassic_Kingdom.png',
            ],
            [
                'code' => '112',
                'name' => 'Oriental Prosperity',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Oriental_Prosperity.png',
            ],
            [
                'code' => '113',
                'name' => 'Raider Jane\'s Crypt of Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Raider_Jane\'s_Crypt_of_Fortune.png',
            ],
            [
                'code' => '114',
                'name' => 'Emoji Riches',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Emoji_Riches.png',
            ],
            [
                'code' => '115',
                'name' => 'Supermarket Spree',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Supermarket_Spree.png',
            ],
            [
                'code' => '117',
                'name' => 'Cocktail Nights',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Cocktail_Nights.png',
            ],
            [
                'code' => '118',
                'name' => 'Mask Carnival',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mask_Carnival.png',
            ],
            [
                'code' => '119',
                'name' => 'Spirited Wonders',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Spirited_Wonders.png',
            ],
            [
                'code' => '120',
                'name' => 'The Queen\'s Banquet',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/The_Queen\'s_Banquet.png',
            ],
            [
                'code' => '121',
                'name' => 'Destiny of Sun & Moon',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Destiny_of_Sun_&_Moon.png',
            ],
            [
                'code' => '122',
                'name' => 'Garuda Gems',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Garuda_Gems.png',
            ],
            [
                'code' => '123',
                'name' => 'Rooster Rumble',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Rooster_Rumble.png',
            ],
            [
                'code' => '124',
                'name' => 'Battleground Royale',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Battleground_Royale.png',
            ],
            [
                'code' => '125',
                'name' => 'Butterfly Blossom',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Butterfly_Blossom.png',
            ],
            [
                'code' => '126',
                'name' => 'Fortune Tiger',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Fortune_Tiger.png',
            ],
            [
                'code' => '127',
                'name' => 'Speed Winner',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Speed_Winner.png',
            ],
            [
                'code' => '128',
                'name' => 'Legend of Perseus',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Legend_of_Perseus.png',
            ],
            [
                'code' => '129',
                'name' => 'Win Win Fish Prawn Crab',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Win_Win_Fish_Prawn_Crab.png',
            ],
            [
                'code' => '130',
                'name' => 'Lucky Piggy',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Lucky_Piggy.png',
            ],
            [
                'code' => '132',
                'name' => 'Wild Coaster',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Wild_Coaster.png',
            ],
            [
                'code' => '135',
                'name' => 'Wild Bounty Showdown',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Wild_Bounty_Showdown.png',
            ],
            // [
            //     'code' => '1312883',
            //     'name' => 'Prosperity Fortune Tree',
            //     'game_type_id' => 1,
            //     'product_id' => 31,
            //     'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/1312883.png',
            // ],
            [
                'code' => '1338274',
                'name' => 'Totem Wonders',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Totem_Wonders.png',
            ],
            [
                'code' => '1340277',
                'name' => 'Asgardian Rising',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Asgardian_Rising.png',
            ],
            [
                'code' => '1368367',
                'name' => 'Alchemy Gold',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Alchemy_Gold.png',
            ],
            [
                'code' => '1372643',
                'name' => 'Diner Delights',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Diner_Delights.png',
            ],
            [
                'code' => '1381200',
                'name' => 'Hawaiian Tiki',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Hawaiian_Tiki.png',
            ],
            [
                'code' => '1397455',
                'name' => 'Fruity Candy',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Fruity_Candy.png',
            ],
            [
                'code' => '1402846',
                'name' => 'Midas Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Midas_Fortune.png',
            ],
            [
                'code' => '1418544',
                'name' => 'Bakery Bonanza',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Bakery_Bonanza.png',
            ],
            [
                'code' => '1420892',
                'name' => 'Rave Party Fever',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Rave_Party_Fever.png',
            ],
            [
                'code' => '1432733',
                'name' => 'Mystical Spirits',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mystical_Spirits.png',
            ],
            [
                'code' => '1448762',
                'name' => 'Songkran Splash',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Songkran_Splash.png',
            ],
            [
                'code' => '1451122',
                'name' => 'Dragon Hatch2',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Dragon_Hatch2.png',
            ],
            [
                'code' => '1473388',
                'name' => 'Cruise Royale',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Cruise_Royale.png',
            ],
            [
                'code' => '1489936',
                'name' => 'Ultimate Striker',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Ultimate_Striker.png',
            ],
            [
                'code' => '1492288',
                'name' => 'Pinata Wins',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Pinata_Wins.png',
            ],
            [
                'code' => '1508783',
                'name' => 'Wild Ape #3258',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Wild_Ape_#3258.png',
            ],
            [
                'code' => '1513328',
                'name' => 'Super Golf Drive',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Super_Golf_Drive.png',
            ],
            [
                'code' => '1529867',
                'name' => 'Ninja Raccoon Frenzy',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Ninja_Raccoon_Frenzy.png',
            ],
            [
                'code' => '1543462',
                'name' => 'Fortune Rabbit',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Fortune_Rabbit.png',
            ],
            [
                'code' => '1555350',
                'name' => 'Forge of Wealth',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Forge_of_Wealth.png',
            ],
            [
                'code' => '1568554',
                'name' => 'Wild Heist Cashout',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Wild_Heist_Cashout.png',
            ],
            [
                'code' => '1572362',
                'name' => 'Gladiator\'s Glory',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Gladiator\'s_Glory.png',
            ],
            [
                'code' => '1580541',
                'name' => 'Mafia Mayhem',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mafia_Mayhem.png',
            ],
            [
                'code' => '1594259',
                'name' => 'Safari Wilds',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Safari_Wilds.png',
            ],
            [
                'code' => '1615454',
                'name' => 'Werewolf\'s Hunt',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Werewolf\'s_Hunt.png',
            ],
            [
                'code' => '1623475',
                'name' => 'Anubis Wrath',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Anubis_Wrath.png',
            ],
            [
                'code' => '1635221',
                'name' => 'Zombie Outbreak',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Zombie_Outbreak.png',
            ],
            [
                'code' => '1655268',
                'name' => 'Tsar Treasures',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Tsar_Treasures.png',
            ],
            [
                'code' => '1671262',
                'name' => 'Gemstones Gold',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Gemstones_Gold.png',
            ],
            [
                'code' => '1682240',
                'name' => 'Cash Mania',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Cash_Mania.png',
            ],
            [
                'code' => '1695365',
                'name' => 'Fortune Dragon',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Fortune_Dragon.png',
            ],
            [
                'code' => '1717688',
                'name' => 'Mystic Potion',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'https://www.luckym.online/assets/slot_app/images/pg_soft/Mystic_Potion.png',
            ],

        ];

        foreach ($data as $gameData) {
            GameList::create($gameData);
        }
    }
}